jobs:
  - name: script-1
    type: runSh
    steps:
      #- IN: sample-script-3
      - IN: trigger-10
      - TASK:
        - script: ls
        - script: echo "ran ls 1234"
        - script: sleep 100
        - script: pwd
  
