jobs:
  - name: script-somerandomshit
    type: runSh
    steps:
      - IN: sample-script
      - IN: triggertest1
      - TASK:
        - script: IN/sample-script/sample-script/echo.sh
  - name: dv-man
    type: manifest
    steps:
      - IN: sn-nginx
        pull: false
      - TASK: managed
      - IN: triggertest1
      - IN: sn-busybox
        pull: false
    on_success:
      - uname -a
      - echo "this works"
      
