jobs:
  - name: script-somerandomscript
    type: runSh
    steps:
      - IN: sample-script
      - IN: triggertest1
      - TASK:
        - script: IN/sample-script/gitRepo/echo.sh
    on_success:
      - script: uname -a
      - script: echo "this works"
    on_failure:
      - script: uname -a
      - script: echo "Inside on failure"

  #- name: dv-man
   # type: manifest
    #steps:
     # - IN: sn-nginx
      #  pull: false
      #- TASK: managed
      #- IN: triggertest1
      #- IN: sn-busybox
      #  pull: false
      
