jobs:
  - name: script-random
    type: runSh
    steps:
      - IN: sample-script
      - IN: triggertest1
      - TASK:
        - script: IN/sample-script/gitRepo/echo.sh
    on_success:
       - script: pwd
       #- script: ls /build
       - script: echo "works!!!"
       - NOTIFY: slackNotifications
    on_failure:
      - script: uname -a
      - script: echo "Inside on failure"

  # - name: dv-man
  #   type: manifest
  #   on_success:
  #     - NOTIFY: slackNotification
  #     - script: uname -a
  #     - script: echo "this works"
  #   on_failure:
  #     - script: uname -a
  #     - script: echo "Inside on failure"
  #   steps:
  #     - IN: sn-nginx
  #       pull: false
  #     - TASK: managed
  #     - IN: triggertest1
  #     - IN: sn-busybox
        # pull: false
      
